export const PANEL_KEYS = {
  FED_RATE: 'fed-rate',
  TREASURY: 'treasury',
  EMPLOYMENT: 'employment',
  INFLATION: 'inflation',
  INFLATION_SUB: 'inflation-sub',
  DOLLAR_INDEX: 'dollar-index',
  GOLD_PRICE: 'gold-price',
  OIL_PRICE: 'oil-price',
  CRYPTO: 'crypto',
  EXCHANGE_RATES: 'exchange-rates',
  US_INDICES: 'us-indices',
  US_STOCKS: 'us-stocks',
  CHINESE_INDICES: 'chinese-indices',
  CHINA_MACRO: 'china-macro',
  CHINA_PMI: 'china-pmi',
  CHINA_TRADE: 'china-trade',
  CHINA_CREDIT: 'china-credit',
  HOUSING_PRICE: 'housing-price',
  CUSTOM_STOCKS: 'custom-stocks',
  PBOC_RATE: 'pboc-rate',
  POLYMARKET: 'polymarket',
} as const;

export type PanelKey = typeof PANEL_KEYS[keyof typeof PANEL_KEYS];

export const PANEL_TITLES: Record<PanelKey, string> = {
  [PANEL_KEYS.FED_RATE]: '美国联邦基金利率（FFR）',
  [PANEL_KEYS.TREASURY]: '美国国债收益率（US Treasury Yields）',
  [PANEL_KEYS.EMPLOYMENT]: '美国劳动力市场（U.S. Labor Market）',
  [PANEL_KEYS.INFLATION]: '美国消费者物价指数（CPI）',
  [PANEL_KEYS.INFLATION_SUB]: '通胀细分指标（CPI & PCE）',
  [PANEL_KEYS.DOLLAR_INDEX]: '美元指数（US Dollar Index）',
  [PANEL_KEYS.GOLD_PRICE]: '国内金价（Gold Price）',
  [PANEL_KEYS.OIL_PRICE]: '油价（Oil Price）',
  [PANEL_KEYS.CRYPTO]: '加密货币行情（Crypto Top 10）',
  [PANEL_KEYS.EXCHANGE_RATES]: '主要汇率（Major Exchange Rates）',
  [PANEL_KEYS.US_INDICES]: '美股指数（US Stock Indices）',
  [PANEL_KEYS.US_STOCKS]: '美股头部股票（含SpaceX代理）',
  [PANEL_KEYS.CHINESE_INDICES]: '中国股市指数（Chinese Stock Indices）',
  [PANEL_KEYS.CHINA_MACRO]: '中国宏观经济指标（China Macro）',
  [PANEL_KEYS.CHINA_PMI]: '中国PMI指标（China PMI）',
  [PANEL_KEYS.CHINA_TRADE]: '中国贸易数据（China Trade）',
  [PANEL_KEYS.CHINA_CREDIT]: '中国信贷数据（China Credit）',
  [PANEL_KEYS.HOUSING_PRICE]: '中国房价行情',
  [PANEL_KEYS.CUSTOM_STOCKS]: '自选股',
  [PANEL_KEYS.PBOC_RATE]: '中国央行利率（PBOC Interest Rates）',
  [PANEL_KEYS.POLYMARKET]: 'Polymarket',
};

// Default panel order (left column then right column from original layout)
export const DEFAULT_ORDER: PanelKey[] = [
  PANEL_KEYS.FED_RATE,
  PANEL_KEYS.TREASURY,
  PANEL_KEYS.EMPLOYMENT,
  PANEL_KEYS.INFLATION,
  PANEL_KEYS.INFLATION_SUB,
  PANEL_KEYS.DOLLAR_INDEX,
  PANEL_KEYS.GOLD_PRICE,
  PANEL_KEYS.OIL_PRICE,
  PANEL_KEYS.CRYPTO,
  PANEL_KEYS.EXCHANGE_RATES,
  PANEL_KEYS.US_INDICES,
  PANEL_KEYS.US_STOCKS,
  PANEL_KEYS.CHINESE_INDICES,
  PANEL_KEYS.CHINA_MACRO,
  PANEL_KEYS.CHINA_PMI,
  PANEL_KEYS.CHINA_TRADE,
  PANEL_KEYS.CHINA_CREDIT,
  PANEL_KEYS.HOUSING_PRICE,
  PANEL_KEYS.CUSTOM_STOCKS,
  PANEL_KEYS.PBOC_RATE,
  PANEL_KEYS.POLYMARKET,
];
